#!/usr/bin/env bash

# CSPIRT - Скрипт для быстрого старта проекта

echo "🚀 CSPIRT - Система управления жалобами и заметками"
echo "=================================================="
echo ""
echo "📋 Доступные команды:"
echo ""
echo "1. Установка зависимостей:"
echo "   npm install (в папке server)"
echo "   npm install (в папке client)"
echo ""
echo "2. Запуск сервера:"
echo "   cd server && npm run dev"
echo "   или"
echo "   cd server && node src/index.js"
echo ""
echo "3. Запуск клиента:"
echo "   cd client && npm run dev"
echo ""
echo "4. Тестирование API:"
echo "   node test-api.js"
echo "   node simple-test.js"
echo ""
echo "=================================================="
echo "📚 Документация:"
echo ""
echo "- QUICKSTART.md  - Быстрый старт"
echo "- README.md      - Полная документация"
echo "- CHANGELOG.md   - Список изменений"
echo "- SUMMARY.md     - Обзор проекта"
echo "- FINAL_REPORT.md - Итоговый отчёт"
echo ""
echo "=================================================="
echo "🔑 Демо-учётные данные:"
echo ""
echo "Admin:   login=admin,  password=password"
echo "User:    login=user1,  password=password"
echo ""
echo "=================================================="

